title: Dicer's blog
subtitle: blog | diary | essay
description: Some blogs about computer sciense and my life.
keywords: Dicer
author: Dicer
language: zh-CN
timezone: null
url: https://blog.dicer.fun
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
auto_spacing: true
titlecase: false
# external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: false
index_generator:
  path: ''
  per_page: 5
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 15
pagination_dir: page
theme: icarus
deploy:
  # type: git
  # repo: 'git@47.101.66.37:/home/git/blog.git'
  # branch: master
  # message: '爷爷奶奶你关注的博主更新啦！'
  type: git
  repo: 'git@42.193.228.103:/home/git/hexo_blog'
  branch: master
  message: '爷爷奶奶你关注的博主更新啦！'
